# Generated by Django 4.2 on 2023-04-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=25, verbose_name='Автор')),
                ('llink', models.CharField(max_length=250, verbose_name='Длинная ссылка')),
                ('slink', models.CharField(max_length=25, verbose_name='Короткая ссылка')),
            ],
        ),
    ]
