# Generated by Django 4.2 on 2023-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slink',
            field=models.CharField(max_length=25, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
