# Generated by Django 4.2 on 2023-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_slink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slink',
            field=models.CharField(max_length=25, verbose_name='Короткая ссылка'),
        ),
    ]
