# Generated by Django 4.2 on 2023-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_alter_link_slink'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('avtor', 'slink'), name='unique_userlink'),
        ),
    ]
